#Build an image from a Dockerfile
FROM maven:3.8.5-openjdk-11 as BUILDER
ARG VERSION=0.0.1-SNAPSHOT
WORKDIR /build/
COPY pom.xml /build/
COPY src /build/src/
RUN mvn clean package
COPY target/custservicemaninfoapi-${VERSION}.jar target/getcustservicemaninfoapi.jar

FROM openjdk:11.0.8-jre-slim
WORKDIR /app/

COPY --from=BUILDER /build/target/getcustservicemaninfoapi.jar /app/

CMD java -jar /app/getcustservicemaninfoapi.jar

# docker build -t custservicemaninfoapi .
# docker run -p 9995:9993 -d custservicemaninfoapi
# localhost:9993/