#Build an image from a Dockerfile
FROM maven:3.8.5-openjdk-11 as BUILDER
ARG VERSION=0.0.1-SNAPSHOT
WORKDIR /build/
COPY pom.xml /build/
COPY src /build/src/
RUN mvn clean package
COPY target/custidsorderidslistpercsmapi-${VERSION}.jar target/getcustidsordidspercsmapi.jar

FROM openjdk:11.0.8-jre-slim
WORKDIR /app/

COPY --from=BUILDER /build/target/getcustidsordidspercsmapi.jar /app/

CMD java -jar /app/getcustidsordidspercsmapi.jar

# docker build -t custidsordidspercsmapi .
# docker run -p 9996:9994 -d custidsordidspercsmapi
# localhost:9996/